export enum TattooStyle {
  MICROREALISM = 'MICROREALISM',
  GEOMETRIC = 'GEOMETRIC',
  TRADITIONAL = 'TRADITIONAL',
  JAPANESE = 'JAPANESE',
  DOTWORK = 'DOTWORK',
  MINIMALIST = 'MINIMALIST',
  TRIBAL = 'TRIBAL',
  WATERCOLOUR = 'WATERCOLOUR',
  REALISTIC = 'REALISTIC',
  ABSTRACT = 'ABSTRACT',
}
