export enum TattooStyle {
  MICROREALISM = 'MICROREALISM',
  GEOMETRIC = 'GEOMETRIC',
  TRADITIONAL = 'TRADITIONAL',
  NEO_TRADITIONAL = 'NEO_TRADITIONAL',
  JAPANESE = 'JAPANESE',
  BLACKWORK = 'BLACKWORK',
  DOTWORK = 'DOTWORK',
  SURREALISM = 'SURREALISM',
  MINIMALIST = 'MINIMALIST',
  LETTERING = 'LETTERING',
}
